name: PR Code Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  scan_js_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Checkout Central Repository for Scripts
        uses: actions/checkout@v3
        with:
          repository: org/central-workflows
          ref: main
          path: central-scripts

      - name: Run JavaScript Linter
        run: |
          node central-scripts/scripts/checkFunctionNames.js || true
        continue-on-error: true  # Ensures the workflow continues even if errors are found

      - name: Upload Comment Output
        if: success() || failure()  # Ensures upload happens even if the previous step fails
        uses: actions/upload-artifact@v3
        with:
          name: pr_comments
          path: comment_output.json  # ✅ Saves the JSON file as an artifact

  comment_on_pr:
    needs: scan_js_files
    runs-on: ubuntu-latest
    steps:
      - name: Download Comment Output
        uses: actions/download-artifact@v3
        with:
          name: pr_comments  # ✅ Downloads the JSON artifact

      - name: Add PR Review Comments
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const issues = JSON.parse(fs.readFileSync('comment_output.json', 'utf8'));
            
            const pr = context.payload.pull_request.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            for (const issue of issues) {
              github.rest.pulls.createReviewComment({
                owner,
                repo,
                pull_number: pr,
                body: issue.message,
                commit_id: context.payload.pull_request.head.sha,
                path: issue.file,
                line: issue.line
              });
            }
