name: PR Code Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  scan_js_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      
      - name: Run JavaScript Linter
        run: node .github/scripts/checkFunctionNames.js
        
      - name: Comment on PR if needed
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: "🚨 Please remove the name 'ranjan' from function names in the PR files."
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
